# Generated by Django 4.0 on 2022-01-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youtube',
            new_name='social_stack_overflow',
        ),
    ]
